stages:
  - test
  - build
  - deploy

code_style:
  image: python:3.7-alpine
  stage: test
  before_script:
    - pip install flake8
  script:
    - flake8

build-app:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_NAME: "app"
    CI_REGISTRY_IMAGE: "registry.gitlab.com/fastpay-pi2/data-visualization"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN registry.gitlab.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest -f ./docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest
  tags:
    - docker
  only:
    - master